# Generated by Django 5.2.8 on 2025-11-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
