# Generated by Django 5.2.8 on 2025-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Fale um pouco sobre você', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='perfil/default.png', null=True, upload_to='perfil/'),
        ),
    ]
