# Generated by Django 5.2.8 on 2025-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
