# Generated by Django 5.2.8 on 2025-11-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil GitHub'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modalidade_trabalho',
            field=models.CharField(blank=True, choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial'), ('qualquer', 'Qualquer')], default='remoto', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='momento_profissional',
            field=models.CharField(blank=True, choices=[('estudante', 'Estudante - Buscando estágio'), ('junior', 'Júnior - Buscando evolução'), ('pleno', 'Pleno - Aberto a propostas'), ('senior', 'Sênior - Especialista'), ('freelancer', 'Freelancer'), ('nao_busco', 'Não estou buscando emprego')], default='estudante', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='Portfólio / Site Pessoal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pretensao_salarial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pretensão Salarial (R$)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Principais Tecnologias (separadas por vírgula)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia / Resumo Profissional'),
        ),
    ]
