# Generated by Django 5.2.8 on 2025-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_cidade_profile_estado_profile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modo_alto_contraste',
            field=models.BooleanField(default=False, verbose_name='Modo de Alto Contraste (Acessibilidade)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfil_publico',
            field=models.BooleanField(default=True, verbose_name='Perfil visível para outros alunos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receber_notificacoes',
            field=models.BooleanField(default=True, verbose_name='Receber novidades e avisos por e-mail'),
        ),
    ]
