# Generated by Django 5.2.8 on 2025-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_modo_alto_contraste_profile_perfil_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(default=20, verbose_name='Carga Horária (Horas)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
